{application,common,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{common_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[common,common_app,common_sup,list_length,mapreduce,
                        my_ssh,node_to_id,qsort]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
