{application,etcd,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{etcd_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[db_application_spec,db_deployment_info,db_deployments,
                        db_host_spec,etcd,etcd_app,etcd_sup,lib_etcd]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
