{application,terminal,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{terminal_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[t,t_lib,terminal_app,terminal_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
